### ISSUE TITLE
SSL Verification

### ISSUE THREAD

**Issue by ProvTommyDunn** [binxio/auth0-login#1]
When you run this the redirect to localhost throws a non-secure form error. Is there any way you can turn off ssl verification?

```This is a non-secure form. This form will be sent in a way that is not secure. Are you sure you want to send it?```

**Comment by mvanholsteijn** [comment]
which browser are you using?

**Comment by ProvTommyDunn** [comment]
This seems to only occur in safari, as far as I know. I was able to solve by serving https, by making the following changes locally. Not sure if there is an easier/better way of doing this.

/auth0-login-master/auth0_login/saml/command.py
change line 17:
from:
from http.server import HTTPServer
to:
from http.server import HTTPServer, BaseHTTPRequestHandler
import ssl

change line 49:
from:
@property
    def callback_url(self):
        return f'http://localhost:{setting.LISTEN_PORT}/saml'
to:
@property
    def callback_url(self):
        return f'https://localhost:{setting.LISTEN_PORT}/saml'

change line 62:
from:
def accept_saml_response(self):
        SAMLAccessTokenCallbackHandler.callback_url = self.callback_url
        SAMLAccessTokenCallbackHandler.handler = (lambda r: self.set_saml_response(r))
        httpd = HTTPServer(('0.0.0.0', self.listen_port), SAMLAccessTokenCallbackHandler)
        httpd.handle_request()
        httpd.server_close()

to:
def accept_saml_response(self):
        SAMLAccessTokenCallbackHandler.callback_url = self.callback_url
        SAMLAccessTokenCallbackHandler.handler = (lambda r: self.set_saml_response(r))
        httpd = HTTPServer(('0.0.0.0', self.listen_port), SAMLAccessTokenCallbackHandler)
        httpd.socket = ssl.wrap_socket (httpd.socket, 
                keyfile="/Users/test/Desktop/auth0-login-master/key.pem", 
                certfile='/Users/test/Desktop/auth0-login-master/cert.pem', server_side=True)
        httpd.handle_request()
        httpd.server_close()

**Comment by mvanholsteijn** [comment]
Well, it is pretty difficult. For https to work, we need a certificate for 'localhost'. However, this is always a self-signed certificate which needs to be added to the trusted CA store of the local machine and/or browser.

**Comment by ProvTommyDunn** [comment]
@mvanholsteijn sorry for the delay in following up on this, I had to switch gears to a different project for a while. Do you know of a way to return the saml response so that it is not in a form?
![Screen Shot 2019-06-08 at 9 54 06 AM](https://user-images.githubusercontent.com/16565460/59151325-e391a580-89e5-11e9-9138-821edbca0348.png)
![Screen Shot 2019-06-08 at 12 02 04 PM](https://user-images.githubusercontent.com/16565460/59151326-e42a3c00-89e5-11e9-8d8d-09a20ba0d283.png)
